# Generated by Django 5.2.6 on 2025-11-03 00:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_comment_notification', models.BooleanField(default=False)),
                ('client_post_notification', models.BooleanField(default=True)),
                ('post_type', models.CharField(choices=[('daily', 'Daily'), ('mood', 'Mood')], max_length=10)),
                ('text', ckeditor.fields.RichTextField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_posts', to='accounts.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_comment_notification', models.BooleanField(default=False)),
                ('client_post_notification', models.BooleanField(default=True)),
                ('post_type', models.CharField(choices=[('daily', 'Daily'), ('mood', 'Mood')], max_length=10)),
                ('mood_emoji', models.CharField(max_length=10)),
                ('energy_level', models.PositiveSmallIntegerField()),
                ('worked_out', models.BooleanField(default=False)),
                ('mood_trigger', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_posts', to='accounts.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
