# Generated by Django 5.2.6 on 2025-11-14 18:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_comment_notification', models.BooleanField(default=False)),
                ('text', ckeditor.fields.RichTextField()),
                ('post_type', models.CharField(default='daily', editable=False, max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_posts', to='accounts.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_comment_notification', models.BooleanField(default=False)),
                ('mood_emoji', models.CharField(max_length=10)),
                ('energy_level', models.PositiveSmallIntegerField()),
                ('worked_out', models.BooleanField(default=False)),
                ('mood_trigger', models.TextField()),
                ('post_type', models.CharField(default='mood', editable=False, max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_posts', to='accounts.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.clientprofile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.therapistprofile')),
                ('daily_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.dailypost')),
                ('mood_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.moodpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
