# Generated by Django 5.2.6 on 2025-11-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypost',
            name='client_post_notification',
        ),
        migrations.RemoveField(
            model_name='moodpost',
            name='client_post_notification',
        ),
    ]
