# Generated by Django 5.2.6 on 2025-11-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypost',
            name='post_type',
            field=models.CharField(default='daily', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='moodpost',
            name='post_type',
            field=models.CharField(default='mood', editable=False, max_length=20),
        ),
    ]
