# Generated by Django 5.2.6 on 2025-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_dailypost_post_type_alter_moodpost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodpost',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
