# Generated by Django 5.2.6 on 2025-11-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_twofactorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='code_type',
            field=models.CharField(choices=[('2fa', 'Two Factor Authentication'), ('password_reset', 'Password Reset')], default='2fa', max_length=20),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='twofactorcode',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
