# Generated by Django 5.2.6 on 2025-11-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_twofa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twofa',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='twofa',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='twofa',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
