# Generated by Django 5.2.6 on 2025-11-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_twofa_clientprofile_twofa_and_more'),
        ('accounts', '0003_twofactorcode_code_type_twofactorcode_token_and_more'),
    ]

    operations = [
    ]
