# Generated by Django 5.2.6 on 2025-11-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251112_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('disconnected', 'Disconnected'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
